### ISSUE TITLE
vector instruction

### ISSUE THREAD

**Issue by lyuchuny3** [gsauthof/riscv#1]
Hi, 
Thanks for your example asm code of riscv vector extension.

I failed to implement the following function
```
void vdot(int n, int8*a, int8*b, int* c)
{
   for i in range(n):
    c[i]=a[4*i]*b[4*i]+a[4*i+1]*b[4*i+1]+a[4*i+2]*b[4*i+2]+a[4*i+3]*b[4*i+3];
}
```
using 
```
# Dot product, SEW=32, EDIV=4
  vdot.vv vd, vs2, vs1
```
in
https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#193-vector-integer-dot-product-instruction

my code is 
```
 vmul:
       slli t1,a0,2
        vsetvli   t0, t1, e8
        vlb.v     v1,(a2)
        vlb.v     v0,(a1)
        vsetvli   t0, a0, e32,m1,d4
        vlw.v     v2,(a3)
        vdot.vv   v2,v0,v1
        vsw.v     v2,(a3)
        ret
```
`An illegal instruction was execute`
Any comments?
Thanks

**Comment by gsauthof** [comment]
How are you running your example? Under Spike?

If you use spike, do you explicitly enable the "V" extension via a command line option (as described in https://gms.tf/riscv-vector.html#getting-started)?

Have you build the pk (as described in https://gms.tf/riscv-vector.html#getting-started)?

Which instruction is reported as illegal?

With Spike, the address of that instruction is reported and thus you can search for it in the `objdump -d` output for your executable.
